In [2]:
import numpy as np

A = np.array([
    [[100, 150, 200], # first row of pixels
     [50, 100, 150],
     [0, 50, 100]],
    
    [[200, 100, 50], # second row 
     [255, 200, 150],
     [100, 0, 50]],
    
    [[25, 75, 125], # third row
     [175, 225, 255],
     [80, 160, 240]]
])

bright = np.clip(A * 1.1, 0, 255)

print("Oryginał:\n", A)
print("\nPo zwiększeniu jasności o 10%:\n", bright)
print("\nTyp danych:", bright.dtype)


Oryginał:
 [[[100 150 200]
  [ 50 100 150]
  [  0  50 100]]

 [[200 100  50]
  [255 200 150]
  [100   0  50]]

 [[ 25  75 125]
  [175 225 255]
  [ 80 160 240]]]

Po zwiększeniu jasności o 10%:
 [[[110.  165.  220. ]
  [ 55.  110.  165. ]
  [  0.   55.  110. ]]

 [[220.  110.   55. ]
  [255.  220.  165. ]
  [110.    0.   55. ]]

 [[ 27.5  82.5 137.5]
  [192.5 247.5 255. ]
  [ 88.  176.  255. ]]]

Typ danych: float64


In [3]:
import numpy as np

x = np.random.randint(0, 256, size=100)
x_scaled = x / 255
mean = np.mean(x)
std = np.std(x)
x_standardized = (x - mean) / std if std != 0 else np.zeros_like(x)

print("mean scaled:", np.mean(x_scaled))
print("mean standardized:", np.mean(x_standardized))
print("std standardized:", np.std(x_standardized))

# jeśli std = 0 - to oznaczałoby to, że nie ma odchylenia, czyli wszystkie dane sa takie same - 
# dla sredniej znormalizowanej rownej 0, oznaczaloby to ze wszystkie dane to zera

mean scaled: 0.4983529411764705
mean standardized: 3.1086244689504386e-17
std standardized: 0.9999999999999998


In [4]:
import numpy as np

x = np.arange(1000)
chunks = x.reshape(10, 100)   # 10 x 100 elementów
means = np.mean(chunks, axis=1) # średnia dla każdego z 10 wierszy

print("shape chunks:", chunks.shape)
print("means:", means)
# axis = 0, oznaczałoby średnia z każdej kolumny, czyli 100 średnich po 10 elementów

shape chunks: (10, 100)
means: [ 49.5 149.5 249.5 349.5 449.5 549.5 649.5 749.5 849.5 949.5]


In [5]:
import numpy as np

X = np.random.randint(0, 100, (5, 4)) # macierz 5 x 4 z losowymi wartościami od 0 do 99
row_mins = X.min(axis=1)
col_maxs = X.max(axis=0)

row_sums = X.sum(axis=1, keepdims=True) # keepdims=True -> shape (5,1)
X_norm = X / row_sums

print("X:\n", X)
print("\nrow_mins:", row_mins)
print("col_maxs:", col_maxs)
print("\nSuma wierszy po normalizacji:", X_norm.sum(axis=1))


X:
 [[29 52 45 37]
 [ 7 61 38 38]
 [87  4 31 55]
 [60 65 54 59]
 [54 96  8 80]]

row_mins: [29  7  4 54  8]
col_maxs: [87 96 54 80]

Suma wierszy po normalizacji: [1. 1. 1. 1. 1.]
