# Lista 3

## Numpy zaawansowane

(8pkt + 3pkt)

Na liście znajduje się 8 zadań do wykonania w trakcie zajęć. Po rozwiązaniu zadania pokaż kod prowadzącemu i odpowiedz na **pytanie kontrolne** — tylko wtedy przyznajemy punkty. Dodatkowo prześlij zadanie na platformie skos.

Jeśli w poleceniu nie jest wskazane użycie pętli `for` - nie korzystaj z niej.

Zadania dodatkowe są oznaczone ⭐️. To zadani o numerach 9, 10, 11 i 12. Punkty zostaną przyznane tylko za rozwiązania z 3 zadań. Rozwiąż te, które najbardziej Ci się podobają.

Każde zadnanie warte jest 1pkt.

## 1. Analiza fragmentów sygnału (slicing)

**Kontekst:**
Masz dane z czujnika EEG zapisane w tablicy `eeg_data` o wymiarach `(1000, 5, 3)` – 1000 próbek, dla 5 pacjentów, a każda próbka ma 3 kanały.
Chcesz przeanalizować wybrane fragmenty sygnału.

**Polecenie**

* Wybierz pierwsze 200 próbek – interesuje Cię początek nagrania.
* Wybierz tylko sygnał nr 1.
* Chcesz sprawdzić trend dla jednego z pacjentów. Dla pacjenta nr 3, z kanału nr 2 wybierz co piątą próbkę.
* Wybierz wyniki dla co 2 dnia i pacjentów o nieparzystych numerach.

**Podpowiedź**
Użyj slicingów `:`, `::`.

In [2]:
import numpy as np

eeg_data = np.random.rand(1000, 5, 3)

# 1. pierwsze 200 próbek
part1 = eeg_data[:200, :, :]

# 2. tylko sygnał nr 1 (czyli kanał nr 0, zakładając indeksowanie od 0)
signal1 = eeg_data[:, :, 0]

# 3. dla pacjenta nr 3, kanał nr 2, co piąta próbka
trend_p3_ch2 = eeg_data[::5, 3, 2]

# 4. wyniki dla co 2 dnia i pacjentów o nieparzystych numerach (1, 3, 5 → czyli indeksy 0, 2, 4)
subset = eeg_data[::2, ::2, :]

print("1. Pierwsze 200 próbek:", part1.shape)
print("2. Sygnał nr 1:", signal1.shape)
print("3. Trend pacjenta nr 3, kanał nr 2:", trend_p3_ch2.shape)
print("4. Co 2 dzień i nieparzyści pacjenci:", subset.shape)

1. Pierwsze 200 próbek: (200, 5, 3)
2. Sygnał nr 1: (1000, 5)
3. Trend pacjenta nr 3, kanał nr 2: (200,)
4. Co 2 dzień i nieparzyści pacjenci: (500, 3, 3)


## 2. Statystyki aktywności modelu (operacje po osiach)

**Kontekst:**
Masz dane `activations` o wymiarach `(3, 500)` – trzy neurony w warstwie modelu, zarejestrowane przez 500 kroków czasowych.
Chcesz zbadać ich zachowanie w czasie.

**Polecenie**

* Oblicz średnią aktywność każdego neuronu w czasie.
* Oblicz średnią aktywność w każdym kroku czasowym.
* Znajdź neuron o najwyższej średniej aktywności – który z trzech był najbardziej „aktywny”?

**Wskazówka:** Przydadzą się `np.mean()` i argument `axis`, oraz `np.argmax()`.

In [3]:
activations = np.random.rand(3, 500)

# 1. średnia aktywność każdego neuronu
mean_per_neuron = np.mean(activations, axis=1)

# 2. średnia aktywność w każdym kroku czasowym
mean_per_step = np.mean(activations, axis=0)

# 3. neuron o najwyższej średniej aktywności
most_active_neuron = np.argmax(mean_per_neuron)

print("1. Średnia aktywność neuronów:", mean_per_neuron)
print("2. Średnia aktywność w krokach czasowych:", mean_per_step[:6])  # pokazujemy tylko kilka
print("3. Najbardziej aktywny neuron:", most_active_neuron)

1. Średnia aktywność neuronów: [0.50277588 0.49732426 0.52428732]
2. Średnia aktywność w krokach czasowych: [0.732782   0.4546743  0.55132441 0.62705814 0.25933355 0.63093686]
3. Najbardziej aktywny neuron: 2


## 3. Podział szeregu czasowego (array_split)

**Kontekst:**
Chcesz przygotować dane do uczenia modelu, który trenuje się na krótszych fragmentach sygnału.

**Polecenie**

Masz daną tablicę `signal = np.arange(100)`. Uywając `np.array_split`:

* Podziel dane na 5 równych fragmentów (czyli po 20 próbek w każdym).
* Podziel dane tak, aby pierwszy zawierał próbki `[:30]`, drugi `[30:70]`, a trzeci `[70:]`.
* Podziel dane na dwie części, tak żeby pierwszy fragment zawierał próbki `[:60]`, a drugi `[60:]`.

In [4]:
signal = np.arange(100)

# 1. 5 równych fragmentów
parts_equal = np.array_split(signal, 5)

# 2. podział wg konkretnych granic
parts_custom = np.array_split(signal, [30, 70])

# 3. podział na dwie części ([:60], [60:])
parts_two = np.array_split(signal, [60])

# wypisz rozmiary
print("1. 5 równych fragmentów:", [p.shape for p in parts_equal])
print("2. Podział [0:30], [30:70], [70:]:", [p.shape for p in parts_custom])
print("3. Podział [0:60], [60:]:", [p.shape for p in parts_two])

1. 5 równych fragmentów: [(20,), (20,), (20,), (20,), (20,)]
2. Podział [0:30], [30:70], [70:]: [(30,), (40,), (30,)]
3. Podział [0:60], [60:]: [(60,), (40,)]


## 4. Funkcje uniwersalne (ufuncs)

**Kontekst:**
Masz dane wejściowe `x` – 200 próbek w zakresie od -3 do 3.
Chcesz policzyć aktywacje typowe dla sieci neuronowych.

**Polecenie:**

* Wygeneruj `x = np.linspace(-3, 3, 200)`.
* Oblicz `sigmoid = 1 / (1 + exp(-x))`.
* Oblicz `relu = max(0, x)`.
* Porównaj średnie wartości tych funkcji.

In [5]:
x = np.linspace(-3, 3, 200)

sigmoid = 1 / (1 + np.exp(-x))
relu = np.maximum(0, x) 

print("Średnia sigmoid:", np.mean(sigmoid))
print("Średnia ReLU:", np.mean(relu))

Średnia sigmoid: 0.5
Średnia ReLU: 0.7537688442211055


## 5. Sortowanie i unikalne wartości

**Kontekst:**
Masz wektor `scores` z wynikami modelu klasyfikującego 100 obserwacji.
Chcesz zobaczyć, które próbki miały najwyższe wyniki i jakie unikalne klasy się pojawiły.

**Polecenie:**

* Wygeneruj losowe `scores` (np. `np.random.rand(100)`).
* Posortuj `scores` rosnąco.
* Zwróć **indeksy** sortowania (czyli w jakiej kolejności należy wziąć próbki).
* Wygeneruj losowy wektor `labels` z wartościami z zakresu `[0, 3]`.
* Wypisz unikalne etykiety i ich liczność.

**Podpowiedź:**
`np.sort`, `np.argsort`, `np.unique(..., return_counts=True)`

In [6]:
# dane
scores = np.random.rand(100)
labels = np.random.randint(0, 4, size=100)

# sortowanie
sorted_scores = np.sort(scores)
sorted_idx = np.argsort(scores)

# unikalne wartości
unique_labels, counts = np.unique(labels, return_counts=True)

print("Posortowane wyniki:", sorted_scores[:5], "...")
print("Indeksy sortowania:", sorted_idx[:5])
print("Unikalne etykiety:", unique_labels)
print("Liczność:", counts)

Posortowane wyniki: [0.01033962 0.01230549 0.0123431  0.02766949 0.04288851] ...
Indeksy sortowania: [58 66 16 49 71]
Unikalne etykiety: [0 1 2 3]
Liczność: [30 25 22 23]


## 6. Łączenie i dzielenie tablic

**Kontekst:**
Masz dane z dwóch sensorów `sensor_A` i `sensor_B`, każdy po 100 próbek.
Chcesz stworzyć jedną tablicę cech oraz przetestować różne sposoby łączenia.

**Polecenie:**

* Wygeneruj dane `sensor_A` i `sensor_B` (np. `np.random.randn(100)`).
* Połącz dane wzdłuż nowej osi.
* Połącz dane wzdłuż istniejącej osi.
* Sprawdź wymiary obu wyników.

**Podpowiedź** `np.concatenate`, `np.stack`

In [7]:
sensor_A = np.random.randn(100)
sensor_B = np.random.randn(100)

# łączenie po nowej osi (powstaje tablica 2 x 100)
stacked = np.stack((sensor_A, sensor_B), axis=0)

# łączenie po istniejącej osi (powstaje wektor 200-elementowy)
concatenated = np.concatenate((sensor_A, sensor_B))

print("stacked shape:", stacked.shape)
print("concatenated shape:", concatenated.shape)

stacked shape: (2, 100)
concatenated shape: (200,)


## 7. Maski i filtrowanie danych (`numpy.ma`)

**Kontekst:**
Masz dane `loss_values` z treningu modelu (np. z 200 epok).
Chcesz sprawdzić, w których momentach **strata spadła poniżej 0.1**, i wygodnie pracować tylko z tymi fragmentami — używając **masked arrays** (`numpy.ma`), które pozwalają ukryć niechciane wartości bez ich usuwania z tablicy.

**Polecenie:**

* Ustaw random seed.
* Wygeneruj `loss_values` – malejący wykres strat (np. `np.linspace(1, 0, 200) + np.random.normal(0, 0.05, 200)`).
* Utwórz **masked array**, która ukryje wartości większe lub równe `0.1`.
* Wyświetl tylko wartości, które **nie są zamaskowane**.
* Policz, w ilu epokach model osiągnął niski błąd (`loss < 0.1`).
* Oblicz średnią z „dobrych” epok, ignorując zamaskowane dane.

**Podpowiedź:**

Użyj: `ma.masked_greater_equal`


In [8]:
import numpy as np
import numpy.ma as ma

# dane

# Ustaw random seed 
# Uzupłnij 
np.random.seed(42)
loss_values = np.linspace(1, 0, 200) + np.random.normal(0, 0.05, 200)

# tworzymy masked array – maskujemy wszystkie wartości >= 0.1
loss_masked = ma.masked_greater_equal(loss_values, 0.1)

# wyświetlamy kilka niezamaskowanych wartości
print("Wartości z niskim błędem:", loss_masked.compressed()[:5])

# liczymy, ile epok miało stratę poniżej 0.1
n_low_loss = loss_masked.count()
print("Liczba epok z niskim błędem:", n_low_loss)

# obliczamy średnią tylko z niezamaskowanych danych
avg_low_loss = loss_masked.mean()
print("Średnia strata (dla niskich wartości):", round(avg_low_loss, 4))

Wartości z niskim błędem: [0.099913   0.0922948  0.04759438 0.03188251 0.06420375]
Liczba epok z niskim błędem: 19
Średnia strata (dla niskich wartości): 0.0316


## 8. Stride tricks

**Kontekst:**
Podczas trenowania modeli w *computer vision* w celu optymalizacji złożoności modelu obrazy dzieli się na mniejsze fragmenty (np. do uczenia na patchach).

**Polecenie:**

Masz obraz o wymiarach **3 × 1000** (obraz czarno-biały o wymiarach 3x1000).

* Wygeneruj dane losowe (np. `np.random.rand(3, 1000)`).
* Użyj `numpy.lib.stride_tricks.sliding_window_view`, by stworzyć macierz okien, tak żeby obrazy nachodziły na siebie co 10 próbek.
* Sprawdź wymiary wynikowej tablicy. Ile masz okien?

**Podpowiedź:** Rozwiązanie powinno być postaci `sliding_window_view(image, window_shape=rozmiar_okna, axis=...)[::krok]`

In [9]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# dane wejściowe
np.random.seed(42)
image = np.random.rand(3, 1000)

# okna o długości 100 pikseli, przesuwane co 10
windows = sliding_window_view(image, window_shape=100, axis=1)
windows1 = windows[:, ::10]
print("Wymiary wynikowej tablicy:", windows.shape)
print(windows1.shape)
print("Liczba okien:", windows1.shape[1])

Wymiary wynikowej tablicy: (3, 901, 100)
(3, 91, 100)
Liczba okien: 91


## ⭐️ 9. Normalizacja niestandardowa

Utwórz `X` o wymiarach `(100, 10)` – 100 obserwacji, 10 cech o różnych zakresach, z zakresu [-100, 100].
Znormalizuj każdą kolumnę **do przedziału od min do max, ale tylko dla wartości dodatnich**.
Wartości ujemne mają pozostać niezmienione.

**Polecenie:**

* Wygeneruj dane `X` z rozkładu normalnego (`np.random.randn(100, 10)`).
* Utwórz maskę `mask = X > 0`.
* Zastosuj broadcastowanie, aby znormalizować każdą kolumnę:

  ```python
  X_norm = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
  ```
* Nałóż maskę tak, aby wartości `≤ 0` w oryginale nie były zmieniane.

**Podpowiedź:**
Użyj `np.where`.

In [10]:
import numpy as np

X = np.random.randn(100, 10) * 100
mask = X > 0
X_norm = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
# if X > 0 then normalized, if X <= 0 then original
X_masked = np.where(mask, X_norm, X) 
print("Przykładowa kolumna przed i po normalizacji:")
print("Oryginalne wartości:", X[:5, 0])
print("Po normalizacji:", X_masked[:5, 0])

Przykładowa kolumna przed i po normalizacji:
Oryginalne wartości: [ 105.9936384  -102.93715082  -15.58981779  -96.37589262 -184.61878622]
Po normalizacji: [   0.79871151 -102.93715082  -15.58981779  -96.37589262 -184.61878622]


## ⭐️ 10. Macierz odległości Euklidesowych w przestrzeni 1000D

Oblicz odległości pomiędzy punktami w bardzo wysokowymiarowej przestrzeni – np. przy analizie embeddingów w modelach językowych.

**Polecenie:**

* Wygeneruj **10 000 punktów w przestrzeni 1000-wymiarowej** (`np.random.rand(10_000, 1000)`).
* Używając **broadcastingu**, oblicz macierz odległości Euklidesowych między wszystkimi parami punktów.
* Zmierz czas wykonania tej operacji.
* Porównaj z implementacją opartą o trzy zagnieżdżone pętle (`for`).

‼ Jeśli twój kod dla 3 pętli będzie trwał dłużej niż 2min - przerwij i wypisz odpowiedni komunikat.

In [11]:
import numpy as np
import time
X = np.random.rand(1000, 1000)
t0 = time.time()
# dist matrix will be 3 dimensional, so we need to stretch the 2d into 3d using empty axis - np.newaxis
dist_matrix = np.sqrt(((X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2).sum(axis=2))

t1 = time.time()
print(f"Using broadcasting in numpy: {t1-t0:.4f} seconds")

t0 = time.time()
dist_slow = np.zeros((1000, 10000))
for i in range(1000):
    for j in range(1000):
        s = 0.0
        for k in range(1000):
            diff = X[i, k] - X[j, k]
            s += diff ** 2
        dist_slow[i, j] = np.sqrt(s)

t1 = time.time()
print(f"Using 3 for loops: {t1-t0:.4f} seconds")
# Dla 10000 punktów był kernel crash, a dla 1000 wyłączyłem po 6 minutach bez wyniku


Using broadcasting in numpy: 20.5554 seconds


KeyboardInterrupt: 

## ⭐️ 11. Stride tricks – zamiana kwadrantów tablicy

Stwórz dwuwymiarową tablicę. **Zamień miejscami górny prawy i dolny lewy kwadrant**, używając tylko `numpy` i `stride_tricks`, bez kopiowania danych.

**Polecenie:**

* Utwórz tablicę `A = np.arange(16).reshape(4, 4)` (dla prostoty).
* Za pomocą `stride_tricks` (np. `as_strided`) lub sprytnego indeksowania stwórz nowy widok tablicy. Twoje rozwiązanie powinno być postaci: `stride_tricks.as_strided(...).reshape(...)`

![task](./Images/ex_np_as_strided.png)


In [12]:
from numpy.lib import stride_tricks as st

A = np.arange(16).reshape(4, 4)
print(A)
# strides = (przejscie o kwadrant w dol, przejscie o kwadrant w prawo, 
# przejscie w dol, przejscie w prawo)
B = st.as_strided(A, shape=(2, 2, 2, 2), strides=(8 * 2, 8 * 4, 64, 8))
print(B)
print(B.reshape(4, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[[ 0  1]
   [ 8  9]]

  [[ 4  5]
   [12 13]]]


 [[[ 2  3]
   [10 11]]

  [[ 6  7]
   [14 15]]]]
[[ 0  1  8  9]
 [ 4  5 12 13]
 [ 2  3 10 11]
 [ 6  7 14 15]]


## ⭐️ 12. Maskowanie warunkowe w macierzach i analiza różnic

**Kontekst:**
Masz dwie macierze wyników modeli `A` i `B` `(1000, 10)`.
Chcesz policzyć różnice i średnie, **ignorując**:

* wszystkie pozycje, w których `A` lub `B` mają NaN,
* wartości ekstremalne (>95 percentyl każdej kolumny),
* wartości ujemne w obu macierzach **jednocześnie**.

**Polecenie:**

1. Wygeneruj `A` i `B` z losowego rozkładu i wprowadź kilka `NaN`.
2. Utwórz maskę, która jednocześnie:

   * maskuje NaN (`masked_invalid`),
   * maskuje wartości > 95 percentyl (`masked_greater`),
   * maskuje pozycje, gdzie `A < 0 & B < 0` (`masked_where` z `logical_and`).
3. Stwórz masked array, która będzie  `diff = |A-B|` z utworzoną powyżej maską.
4. Policz średnią i wariancję różnic macierzy `diff`, ignorując zamaskowane wartości.
5. Zastąp zamaskowane wartości średnią kolumnową.

**Podpowiedź**

Z biblioteki `numpy.ma` mogą się przydać:
`masked_invalid`, `masked_greater`, `masked_where`, `mask_or`, `mean`, `var`, `filled`.

Z biblioteki `numpy` przydadzą się: `np.percentile`, `np.logical_and`.

In [ ]:
import numpy as np
import numpy.ma as ma

np.random.seed(42)
A = np.random.randn(1000, 10) * 10   
B = np.random.randn(1000, 10) * 10

nan_mask = np.random.rand(1000, 10) < 0.05
A[nan_mask] = np.nan
B[nan_mask] = np.nan

mask_nan = np.logical_or(ma.masked_invalid(A), ma.masked_invalid(B))
percentiles_A = np.percentile(A[np.isfinite(A)], 95)
percentiles_B = np.percentile(B[np.isfinite(B)], 95)
mask_extreme = np.logical_or(ma.masked_greater(A, percentiles_A), ma.masked_greater(B, percentiles_B))
mask_both_neg = ma.masked_where(np.logical_and(A < 0, B < 0), A)

combined_mask = ma.mask_or(mask_nan.mask, mask_extreme.mask)
combined_mask = ma.mask_or(combined_mask, mask_both_neg.mask)

diff = ma.masked_array(np.abs(A - B), mask=combined_mask)
mean_diff = diff.mean()
var_diff = diff.var()

print(f"Średnia różnic: {mean_diff:.4f}")
print(f"Wariancja różnic: {var_diff:.4f}")

col_means = ma.mean(diff, axis=0)
diff_filled = diff.filled(col_means)

print("\nPrzykład wynikowej macierzy diff (pierwsze 5 wierszy):")
print(diff_filled[:5])

Średnia różnic: 11.6722
Wariancja różnic: 62.3359

Przykład wynikowej macierzy diff (pierwsze 5 wierszy):
[[11.75208883 11.53987633 12.45069599 14.12611809 14.31331906 11.61341147
  11.46145026 15.49106801 12.13342292  2.76034575]
 [13.85354071 13.1713969  15.5775968  12.12030062 25.47906425  6.0382937
  11.46145026  1.44070607 12.13342292 11.12874101]
 [ 0.79192693  8.29873727 12.934785   14.89539536 13.09820219 13.66797706
  13.96492259  6.3088519  12.13342292 11.12874101]
 [14.25129797 11.53987633  5.1786229  12.12030062 27.99366481 11.61341147
  11.46145026 11.38807424 19.46742406 11.12874101]
 [ 6.14937378  3.8810007  11.84429446  4.25488462 11.83455825  8.40042767
   9.11451107  8.47436163  1.13923644 11.12874101]]
